seed: 42
device: "auto"

# --- Data ---
data:
  dataset: "cifar10"
  data_dir: "./data"
  num_samples: 10
  batch_size: 10

# --- Threat model ---
threat_model:
  norm: "Linf"
  epsilon: 0.03137254901960784   # 8/255

# --- Surrogate models ---
enable_single_surrogate_attacks: false

surrogates:
  - name: "Standard"
    source: "robustbench"
    needs_normalize: false

  - name: "cifar10_vgg16_bn"
    source: "chenyaofo"
    needs_normalize: true

  - name: "cifar10_resnet56"
    source: "chenyaofo"
    needs_normalize: true

  - name: "cifar10_mobilenetv2_x1_4"
    source: "chenyaofo"
    needs_normalize: true

  - name: "cifar10_repvgg_a2"
    source: "chenyaofo"
    needs_normalize: true

# --- Target robust models ---
targets:
  # - name: "Carmon2019Unlabeled"
  #   source: "robustbench"
  #   needs_normalize: false

  # - name: "Chen2020Adversarial" # ResNet-50
  #   source: "robustbench"
  #   needs_normalize: false

  # - name: 'Kang2021Stable'  # WideResNet-70-16
  #   source: "robustbench"
  #   needs_normalize: false
  
  # - name: 'Bartoldson2024Adversarial_WRN-94-16' # WideResNet-94-16
  #   source: "robustbench"
  #   needs_normalize: false

  # - name: "Rebuffi2021Fixing_70_16_cutmix_extra"  # WideResNet-70-16
  #   source: "robustbench"
  #   needs_normalize: false

  # - name: "Wang2023Better_WRN-70-16"  # WideResNet-70-16
  #   source: "robustbench"
  #   needs_normalize: false

  # - name: "Gowal2021Improving_28_10_ddpm_100m"  # WideResNet-28-10
  #   source: "robustbench"
  #   needs_normalize: false
  
  - name: "Sehwag2021Proxy_R18" # ResNet-18
    source: "robustbench"
    needs_normalize: false
  
  - name: "Addepalli2022Efficient_RN18" # ResNet-18
    source: "robustbench"
    needs_normalize: false

  - name: "Xu2023Exploring_WRN-28-10" # WideResNet-28-10
    source: "robustbench"
    needs_normalize: false

# --- Attacks ---
attacks:
  # - name: "MIFGSM"
  #   params:
  #     steps: 10
  #     decay: 1.0

  # - name: "DIFGSM"
  #   params:
  #     steps: 10
  #     decay: 1.0
  #     resize_rate: 0.9
  #     diversity_prob: 1.0

  # - name: "TIFGSM"
  #   params:
  #     steps: 10
  #     decay: 1.0
  #     kern_len: 15
  #     n_sig: 3

  - name: "SINIFGSM"
    params:
      steps: 10
      decay: 1.0
      m: 3

  - name: "Admix"
    params:
      steps: 10
      decay: 1.0
      portion: 0.2
      size: 3
      num_classes: 10

  # - name: "VMIFGSM"
  #   params:
  #     steps: 10
  #     decay: 1.0
  #     n: 5
  #     beta: 1.5

# --- Ensemble surrogate attack ---
ensemble:
  enabled: true

# --- Output ---
output:
  results_dir: "./results"
  save_csv: true
  save_plots: true
  save_adv_examples: true

# --- Model cache ---
model_dir: "./models"
